# Generated by Django 4.1.7 on 2023-05-15 12:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_id", models.IntegerField()),
                ("tag_name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Scotops",
            fields=[
                ("scoto_id", models.IntegerField(primary_key=True, serialize=False)),
                ("scoto_name", models.CharField(max_length=100)),
                ("scoto_idea", models.CharField(max_length=10000)),
                ("scoto_datetime", models.DateTimeField(default=datetime.datetime.now)),
                ("scoto_auther", models.CharField(max_length=10000)),
                (
                    "scoto_tag1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="TA",
                        to="Scotopia.tags",
                    ),
                ),
                (
                    "scoto_tag2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="TB",
                        to="Scotopia.tags",
                    ),
                ),
                (
                    "scoto_tag3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="TC",
                        to="Scotopia.tags",
                    ),
                ),
            ],
        ),
    ]
