# Generated by Django 4.1.7 on 2023-05-15 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Scotopia", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scotops",
            name="scoto_tag2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="TB",
                to="Scotopia.tags",
            ),
        ),
        migrations.AlterField(
            model_name="scotops",
            name="scoto_tag3",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="TC",
                to="Scotopia.tags",
            ),
        ),
    ]
