# Generated by Django 4.1.7 on 2023-05-16 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Scotopia", "0003_alter_scotops_scoto_tag2_alter_scotops_scoto_tag3"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.IntegerField()),
                ("uname", models.CharField(max_length=100)),
                ("upassword", models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name="scotops",
            name="scoto_tag1",
        ),
        migrations.RemoveField(
            model_name="scotops",
            name="scoto_tag2",
        ),
        migrations.RemoveField(
            model_name="scotops",
            name="scoto_tag3",
        ),
        migrations.AddField(
            model_name="scotops",
            name="scoto_tag",
            field=models.ManyToManyField(
                blank=True, related_name="TA", to="Scotopia.tags"
            ),
        ),
        migrations.RemoveField(
            model_name="scotops",
            name="scoto_auther",
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_content", models.CharField(max_length=1000)),
                (
                    "c_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Scotopia.scotops",
                    ),
                ),
                (
                    "c_ter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commeter_name",
                        to="Scotopia.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="scotops",
            name="scoto_auther",
            field=models.ManyToManyField(
                max_length=10000, related_name="Auther_names", to="Scotopia.user"
            ),
        ),
    ]
