# Generated by Django 4.1.7 on 2023-05-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Scotopia", "0005_category_scotops_scoto_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scotops",
            name="scoto_idea",
        ),
        migrations.AddField(
            model_name="comments",
            name="c_likes",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="scotops",
            name="scoto_idea_brief",
            field=models.CharField(default="No idea", max_length=120),
        ),
        migrations.AddField(
            model_name="scotops",
            name="scoto_idea_details",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="scotops",
            name="scoto_likes",
            field=models.IntegerField(default=1),
        ),
    ]
