# Generated by Django 4.1.7 on 2023-05-16 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Scotopia", "0006_remove_scotops_scoto_idea_comments_c_likes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scotops",
            name="scoto_category",
            field=models.ForeignKey(
                default="Uncategorised",
                max_length=1000,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Scotopia.category",
            ),
        ),
    ]
