# Generated by Django 4.1.7 on 2023-05-16 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Scotopia", "0011_scotops_scoto_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scotops",
            name="scoto_likes",
        ),
    ]
