# Generated by Django 4.1.7 on 2023-05-27 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Scotopia", "0012_remove_scotops_scoto_likes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="c_id",
            new_name="C_id",
        ),
        migrations.RenameField(
            model_name="comments",
            old_name="c_content",
            new_name="Comment",
        ),
        migrations.RemoveField(
            model_name="comments",
            name="c_likes",
        ),
        migrations.RemoveField(
            model_name="comments",
            name="c_ter",
        ),
        migrations.RemoveField(
            model_name="user",
            name="uid",
        ),
        migrations.RemoveField(
            model_name="user",
            name="uname",
        ),
        migrations.RemoveField(
            model_name="user",
            name="upassword",
        ),
        migrations.AddField(
            model_name="comments",
            name="Commenter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Commenter",
                to="Scotopia.user",
            ),
        ),
        migrations.AddField(
            model_name="comments",
            name="liked",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="LikedComment",
                to="Scotopia.user",
            ),
        ),
        migrations.AddField(
            model_name="scotops",
            name="liked",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Scotopia.user",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(related_name="Gps", to="Scotopia.user"),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(related_name="ups", to="Scotopia.user"),
        ),
        migrations.AlterField(
            model_name="scotops",
            name="scoto_auther",
            field=models.ManyToManyField(
                related_name="Auther_names", to="Scotopia.user"
            ),
        ),
        migrations.AlterField(
            model_name="scotops",
            name="scoto_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Scotopia.category"
            ),
        ),
        migrations.AlterField(
            model_name="scotops",
            name="scoto_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
