# Generated by Django 4.1.7 on 2023-05-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Scotopia", "0013_rename_c_id_comments_c_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scotops",
            name="image",
            field=models.ImageField(
                default="Scotopia\\static\\Yorsy.jpg", upload_to="blog\\%Y\\%m"
            ),
        ),
    ]
