# Generated by Django 4.1.7 on 2023-05-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Scotopia", "0014_scotops_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                null=True, related_name="Gps", to="Scotopia.user"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                null=True, related_name="ups", to="Scotopia.user"
            ),
        ),
    ]
