# Generated by Django 4.1.7 on 2023-05-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Scotopia", "0015_alter_user_groups_alter_user_user_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
    ]
