# Generated by Django 4.1.7 on 2023-05-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Scotopia", "0016_remove_user_groups_remove_user_user_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scotops",
            name="liked",
        ),
        migrations.AddField(
            model_name="scotops",
            name="liked",
            field=models.ManyToManyField(related_name="likedBy", to="Scotopia.user"),
        ),
    ]
