# Generated by Django 4.1.7 on 2023-06-04 13:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("C_id", models.IntegerField()),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("P_id", models.IntegerField()),
                ("name", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("T_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("P_id", models.IntegerField()),
                ("title", models.CharField(max_length=60)),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 6, 4, 19, 8, 33, 195579)
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("details", models.CharField(blank=True, max_length=1500, null=True)),
                (
                    "image",
                    models.ImageField(
                        default="App\\static\\Yorsy.jpg",
                        upload_to="post\\<django.db.models.fields.IntegerField>",
                    ),
                ),
                (
                    "auther",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="App.persona"
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(related_name="Category", to="App.category"),
                ),
                (
                    "likedby",
                    models.ManyToManyField(
                        null=True, related_name="liked", to="App.persona"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("C_id", models.IntegerField()),
                ("comment", models.CharField(max_length=100)),
                (
                    "auther",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="App.persona"
                    ),
                ),
                (
                    "liked",
                    models.ManyToManyField(
                        related_name="Commentlikedby", to="App.persona"
                    ),
                ),
            ],
        ),
    ]
