# Generated by Django 4.1.7 on 2023-06-13 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0003_tags_name_alter_post_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="id",
        ),
        migrations.AlterField(
            model_name="post",
            name="P_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 13, 23, 13, 35, 998472)
            ),
        ),
    ]
