# Generated by Django 4.1.7 on 2023-06-13 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0004_remove_post_id_alter_post_p_id_alter_post_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 13, 23, 14, 5, 23565)
            ),
        ),
    ]
