# Generated by Django 4.1.7 on 2023-06-13 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0005_alter_post_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
        migrations.AddField(
            model_name="post",
            name="P_tags",
            field=models.ManyToManyField(related_name="PTags", to="App.tags"),
        ),
        migrations.AddField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="P_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 13, 23, 17, 41, 410829)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="likedby",
            field=models.ManyToManyField(related_name="liked", to="App.persona"),
        ),
    ]
