# Generated by Django 4.1.7 on 2023-06-14 16:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0011_alter_post_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Granger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("P_id", models.IntegerField()),
                ("title", models.CharField(max_length=60)),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 6, 14, 21, 33, 18, 314954)
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("details", models.CharField(blank=True, max_length=1500, null=True)),
                (
                    "image",
                    models.ImageField(
                        default="App\\static\\Yorsy.jpg",
                        upload_to="post\\<django.db.models.fields.IntegerField>",
                    ),
                ),
                ("P_tags", models.ManyToManyField(related_name="PTags", to="App.tags")),
                (
                    "auther",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="App.persona"
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(related_name="Category", to="App.category"),
                ),
                (
                    "likedby",
                    models.ManyToManyField(related_name="liked", to="App.persona"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
