# Generated by Django 4.1.7 on 2023-06-14 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0012_granger_delete_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="auther",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="liked",
        ),
        migrations.RemoveField(
            model_name="granger",
            name="P_tags",
        ),
        migrations.RemoveField(
            model_name="granger",
            name="auther",
        ),
        migrations.RemoveField(
            model_name="granger",
            name="category",
        ),
        migrations.RemoveField(
            model_name="granger",
            name="likedby",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Granger",
        ),
        migrations.DeleteModel(
            name="Tags",
        ),
    ]
